# Don't touch
collections:
  - staff_members
  - publications

permalink: pretty

gems:
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
    values:
      layout: "default"

# Ok to change
url: http://nunemakerlab.hcom.ohio.edu/
baseurl:
google_analytics_key: UA-98231289-2
news:
  show_dates: false

copyright: "Ohio University is a trademark of Ohio University; Rakefire is a trademaker of Rakefire LLC"

lab:
  name: Nunemaker Lab
  tag_line: Finding and fixing the earliest signs of failure in insulin-producing beta-cells
  keywords: "diabetes research, diabetes, research, Craig Nunemaker, Diabetes Institute, Ohio University"
  description: Finding and fixing the earliest signs of failure in insulin-producing beta-cells
  attribution:
    university:
      name: Ohio University
      short: OHIO
      logo: /images/logos/ohio_wht.svg
      url: https://www.ohio.edu/
    college:
      name: Heritage College of Osteopathic Medicine
      short: HCOM
      logo: /images/logos/hcom.png
      url: https://www.ohio.edu/medicine/
  contact:
    address: Academic and Research Center Room 302C, Ohio University, Athens, Ohio
    phone:
    email: nunemake@ohio.edu
    facebook:
    twitter:
    google_plus:
  quote:
    text: Our laboratory is devoted to finding and fixing the earliest signs of failure in insulin-producing beta-cells that lead to diabetes.
    color: "#fff"

form_submission:
  action: http://formspree.io/
  email: nunemake@ohio.edu
form:
  background:
    placeholder: I'm a senior at ___________ studying ____________________. I'm interested in joining your lab for graduate studies. I'd like to focus research on...  Please do not enter any sensitive/confidential information (i.e. grades, student ID, financial need, or any FERPA data)
