# Don't touch
collections:
  - staff_members
  - publications

permalink: pretty

gems:
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
    values:
      layout: "default"

# Ok to change
url: http://nunemakerlab.hcom.ohio.edu/
baseurl:
google_analytics_key: UA-98231289-2

copyright: "Ohio University is a trademark of Ohio University; Rakefire is a trademaker of Rakefire LLC"

lab:
  name: Lee Lab
  tag_line: Understanding the Biology of Adipocytes
  keywords: "diabetes research, diabetes, research, fat cells, Kevin Lee, Diabetes Institute, Ohio University, adipocytes, adipose"
  description: Uncover molecular and functional differences between morphologically indistinguishable fat cells at Ohio University.
  attribution:
    university:
      name: Ohio University
      short: OHIO
      logo: /images/logos/ohio_wht.svg
      url: https://www.ohio.edu/
    college:
      name: Heritage College of Osteopathic Medicine
      short: HCOM
      logo: /images/logos/hcom.png
      url: https://www.ohio.edu/medicine/
  contact:
    address: Academic and Research Center Room 202e, Ohio University, Athens, Ohio
    phone: 740-593-2327
    email: leek2@ohio.edu
    facebook:
    twitter:
    google_plus:
  quote:
    text: Our lab seeks to uncover molecular and functional differences between morphologically indistinguishable fat cells.
    color: "#fff"

form_submission:
  action: http://formspree.io/
  email: leek2@ohio.edu
form:
  background:
    placeholder: I'm a senior at ___________ studying ____________________. I'm interested in joining your lab for graduate studies. I'd like to focus research on...  Please do not enter any sensitive/confidential information (i.e. grades, student ID, financial need, or any FERPA data)
